CREATE DATABASE MATRICULA
USE MATRICULA

CREATE TABLE ALUMNO (
  ID_ALUMNO INT AUTO_INCREMENT PRIMARY KEY,
  DNI_ALUMNO CHAR(8) UNIQUE NOT NULL,
  NOMBRES VARCHAR(50) NOT NULL,
  APELLIDOS VARCHAR(50) NOT NULL,
  FECHA_NACIMIENTO DATE NOT NULL,
  EDAD INT NOT NULL,
  GENERO CHAR(1) NOT NULL, 
  DIRECCION VARCHAR(100) NOT NULL,
  CELULAR CHAR(9) NOT NULL,
  CORREO VARCHAR(80) UNIQUE NOT NULL,
  NOMBRE_APODERADO VARCHAR(50) NOT NULL,
  CELULAR_APODERADO CHAR(9) NOT NULL,
  USERNAME VARCHAR(50) UNIQUE NOT NULL,
  PASSWORD_HASH VARCHAR(255) NOT NULL,
  FECHA_REGISTRO DATETIME DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE ALUMNO
ADD ESTADO CHAR(1) NOT NULL DEFAULT 'A';

CREATE TABLE AULA (
ID_AULA INT AUTO_INCREMENT PRIMARY KEY,
NIVEL VARCHAR(30) NOT NULL,
GRADO INT NOT NULL,
SECCION CHAR(1) NOT NULL,
VACANTES_TOTALES INT NOT NULL,
VACANTES_DISPONIBLES INT NOT NULL
);

CREATE TABLE RESERVA (
ID_RESERVA INT AUTO_INCREMENT PRIMARY KEY,
ID_ALUMNO INT NOT NULL,
ID_AULA INT NOT NULL,
CODIGO_PAGO VARCHAR(20) UNIQUE NOT NULL,
FECHA_RESERVA DATETIME DEFAULT CURRENT_TIMESTAMP,
ESTADO_PAGO VARCHAR(20) DEFAULT 'PENDIENTE'
);

CREATE TABLE USUARIO(
ID INT AUTO_INCREMENT PRIMARY KEY,
USERNAME VARCHAR(50) UNIQUE NOT NULL,
PASSWORD_HASH VARCHAR(200) NOT NULL,
ESTADO TINYINT(1) DEFAULT 1
);

CREATE TABLE CURSO (
  ID_CURSO INT AUTO_INCREMENT PRIMARY KEY,
  NOMBRE VARCHAR(50) NOT NULL,
  DESCRIPCION VARCHAR(100),
  HORAS_SEMANA INT NOT NULL
);

-- RELACIONES --
ALTER TABLE RESERVA
ADD CONSTRAINT FK_RELACION1
FOREIGN KEY (ID_ALUMNO) REFERENCES ALUMNO (ID_ALUMNO);

ALTER TABLE RESERVA
ADD CONSTRAINT FK_RELACION2
FOREIGN KEY (ID_AULA) REFERENCES AULA (ID_AULA);

--INSERCIONES--

INSERT INTO ALUMNO (
  DNI_ALUMNO, NOMBRES, APELLIDOS, FECHA_NACIMIENTO, EDAD, GENERO, 
  DIRECCION, CELULAR, CORREO, NOMBRE_APODERADO, CELULAR_APODERADO, 
  USERNAME, PASSWORD_HASH
) VALUES (
  '12345643', 'Juan Carlos', 'Perez Lopez', '2005-03-15', 20, 'M',
  'Av. Siempre Viva 123', '987654321', 'juanpercz@gmail.com',
  'Maria Lopez', '912345678', 'juanpewez', 'hash123'
);
INSERT INTO ALUMNO (
DNI_ALUMNO, NOMBRES, APELLIDOS, FECHA_NACIMIENTO, EDAD, GENERO,
DIRECCION, CELULAR, CORREO, NOMBRE_APODERADO, CELULAR_APODERADO,
USERNAME, PASSWORD_HASH
) VALUES
(
'78451236', 'Luis Alberto', 'Gomez Ruiz', '2008-05-10', 16, 'M',
'Av. Los Olivos 456', '987654111', 'luisgomez@gmail.com',
'Carlos Gomez', '912345111', 'luisg', 'hash123'
),

(
'45678912', 'Maria Fernanda', 'Torres Silva', '2010-09-22', 14, 'F',
'Jr. Lima 789', '987654222', 'mariatorres@gmail.com',
'Rosa Silva', '912345222', 'mariat', 'hash123'
);

INSERT INTO AULA (nivel, grado, seccion, vacantes_totales, vacantes_disponibles) VALUES
('Secundaria', 3, 'A', 30, 5),
('Secundaria', 3, 'B', 30, 0),
('Primaria', 1, 'A', 25, 25),
('Primaria', 6, 'B', 30, 12);

INSERT INTO RESERVA (ID_ALUMNO, ID_AULA, CODIGO_PAGO, ESTADO_PAGO) VALUES
(1, 1, 'PAGO001', 'PENDIENTE'),
(2, 2, 'PAGO002', 'PAGADO'),
(3, 3, 'PAGO003', 'PENDIENTE');

INSERT INTO USUARIO (USERNAME, PASSWORD_HASH)
VALUES ('Admin', '$2y$10$heuMG7aElXF5IiS4rCN49.T.smRQfhlCmVuoAh/SPpjQ6YA6qzZO6')

INSERT INTO CURSO (NOMBRE, DESCRIPCION, HORAS_SEMANA) VALUES
('Matemática', 'Curso de razonamiento lógico y cálculo', 5),
('Comunicación', 'Comprensión lectora y redacción', 4),
('Ciencia y Tecnología', 'Ciencias naturales y experimentación', 3);

DROP DATABASE IF EXISTS MATRICULA;
